Repository surrealdb/www.surrealdb.com, pull requests merged in 2023-04, with the labels that each got.

#95 fix digitalocean link
  app/templates/docs/deployment/index.hbs
Labels: bug

#98 Document "Deploy to Fly.io"
  app/initializers/prism.js
  app/instance-initializers/marked.js
  app/snippets/docs/deployment/fly.io/Dockerfile.docker
  app/snippets/docs/deployment/fly.io/create-working-directory.sh
  app/snippets/docs/deployment/fly.io/fly-create-volume.sh
  app/snippets/docs/deployment/fly.io/fly-deploy.sh
  app/snippets/docs/deployment/fly.io/fly-launch.sh
  app/snippets/docs/deployment/fly.io/fly-toml-add-volume.toml
  app/snippets/docs/deployment/fly.io/set-root-authentication.sh
  app/templates/docs/deployment/fly.hbs
  ember-cli-build.js
Labels: documentation

#101 Group all, not BY all
  app/templates/docs/surrealql/functions/count.hbs
Labels: documentation

#102 Patch: Update Blocks introduction query
  app/components/section/releases/v1-0-0-beta-9.hbs
Labels: bug, documentation

#103 Patch account query on quick start page
  app/snippets/docs/start/index/step5.bash
  app/snippets/docs/start/index/step5.surql
Labels: bug, documentation

#108 Docs: Beta-8 to beta-9 migration guide
  app/router.js
  app/templates/docs.hbs
  app/templates/docs/installation/index.hbs
  app/templates/docs/installation/upgrading/beta8-to-beta9.hbs
Labels: documentation
